"""create tables

Revision ID: bc4a1c942b0b
Revises: 
Create Date: 2019-08-06 23:01:02.773751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc4a1c942b0b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('poll',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suggestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('user_username', sa.String(length=255), nullable=True),
    sa.Column('user_title', sa.String(length=255), nullable=True),
    sa.Column('text', sa.String(length=255), nullable=True),
    sa.Column('file_id', sa.String(length=255), nullable=True),
    sa.Column('user_message_id', sa.Integer(), nullable=True),
    sa.Column('forwarded_from_id', sa.String(length=255), nullable=True),
    sa.Column('forwarded_from_username', sa.String(length=255), nullable=True),
    sa.Column('forwarded_from_title', sa.String(length=255), nullable=True),
    sa.Column('admin_message_id', sa.Integer(), nullable=True),
    sa.Column('decision', sa.String(length=30), nullable=True),
    sa.Column('channel_post_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('poll_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(length=4), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('poll_vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=True),
    sa.Column('option_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['option_id'], ['poll_option.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poll_vote')
    op.drop_table('poll_option')
    op.drop_table('suggestion')
    op.drop_table('poll')
    op.drop_table('admin_state')
    # ### end Alembic commands ###
